[package]
name = "fri"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/ndwrobotics/fri"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-std = "0.5.0"
rs_merkle = "1.5.0"
